### ISSUE TITLE
Display filesystems metrics

### ISSUE THREAD

**Issue by geoffreypetri** [geoffreypetri/cyclope#10]
- [ ] Display backup filesystem usage
- [ ] Display number of backups
- [ ] Give access to backup logs
- [ ] Display data filesystem usage
- [ ] Display backup filesystem usage progression
- [ ] Display data filesystem usage progression
- [ ] Display user comments
