### ISSUE TITLE
Watch data filesystem

### ISSUE THREAD

**Issue by geoffreypetri** [geoffreypetri/cyclope#8]
- [ ] Get data filesystem usage
- [ ] Get current data filesystem usage
- [ ] Log data filesystem information
- [ ] Provide data filesystem usage progression
- [ ] Warn on data filesystem usage
